# Generated by Django 3.0.3 on 2020-03-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
    ]
